<h1>Index</h1>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-6">

            <?php foreach ($this->view->data as $key => $product) { ?>

                <h2>Description: </h2>
                <p><?= $product['description'] ?></p>
                <h4>Price: </h4>
                <p><?= $product['price'] ?></p>

            <?php } ?>

        </div>
    </div>
</div>


